### ISSUE TITLE
Readme.MD

### ISSUE THREAD

**Issue by sarthakpant772** [sarthakpant772/desiTwitter#1]
Make a good readme for both server and client-side and also in general.

**Comment by IrfanSalim** [comment]
Hey, I would like to work on this, please assign.

**Comment by Shreya111111** [comment]
@sarthakpant772 can i work on this issue

**Comment by sarthakpant772** [comment]
Hey, @Shreya111111 right now someone else is working on this issue. You can check out other issues/ open new Issues till then

**Comment by IrfanSalim** [comment]
Hey @sarthakpant772 

Sorry about the delay with the issue, I'm almost done with the changes and will raise the PR by tomorrow.

Thanks for your patience

**Comment by IrfanSalim** [comment]
Hey @sarthakpant772

Could you please add the hacktoberfest tag to this and also fix the capitalization in the parent issue (all chars should be small case). This is not reflecting on my dashboard.

Thanks

**Comment by sarthakpant772** [comment]
Done
